name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5433/testdb

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack and install Yarn 4.9.1
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          yarn set version 4.9.1

      - name: Install dependencies
        run: yarn install

      - name: Reset and migrate database (force, non-interactive)
        run: yarn prisma migrate reset --force --skip-seed --skip-generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5433/testdb

      - name: Generate Prisma client
        run: yarn prisma generate

    #   - name: Run tests
    #     run: yarn test
    #     env:
    #       DATABASE_URL: postgresql://postgres:postgres@localhost:5433/testdb
